apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: helm-upgrade-from-source
spec:
  taskRef:
    name: helm-upgrade-from-source
  params:
    - name: charts_dir
      value: ./helm-task
    - name: releases_version
      value: v1.0.0
    - name: release_name
      value: helm-source-task
    - name: overwrite_values
      value: "autoscaling.enabled=true,autoscaling.maxReplicas=3"
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: my-source
