apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-me
  template:
    metadata:
      labels:
        app: app-me
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: {{ .Values.user }}
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-pass
                  key: key
            - name: ME_CONFIG_MONGODB_SERVER
              value: {{ .Values.pathDB }}
#            - name: ME_CONFIG_MONGODB_URL
#              value: mongodb://{{ .Values.user  }}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@{{ .Values.pathDB }}:27017/
          ports:
            - containerPort: 8081
